AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvType:
    Type: String
    Default: dev

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub kanban-static-${EnvType}

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: KanbanTasks
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: kanban-cluster

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: kanbanLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ses:SendEmail
                Resource: "*"

